version: '3'
services:
  arangodb:
    image: arangodb/arangodb:3.4.3
    container_name: arangodb
    ports:
      - "${ARANGO_PORT:-8529}:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_PASSWORD:-letmein}
    volumes:
      - "${ARANGO_DATA:-/var/arangodb}:/var/lib/arangodb3"
      - "${ARANGO_DATA:-/var/arangodb}-apps:/var/lib/arangodb-apps"
